//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace empreview
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class empreviewtrackEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new empreviewtrackEntities1 object using the connection string found in the 'empreviewtrackEntities1' section of the application configuration file.
        /// </summary>
        public empreviewtrackEntities1() : base("name=empreviewtrackEntities1", "empreviewtrackEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new empreviewtrackEntities1 object.
        /// </summary>
        public empreviewtrackEntities1(string connectionString) : base(connectionString, "empreviewtrackEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new empreviewtrackEntities1 object.
        /// </summary>
        public empreviewtrackEntities1(EntityConnection connection) : base(connection, "empreviewtrackEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<roletable> roletables
        {
            get
            {
                if ((_roletables == null))
                {
                    _roletables = base.CreateObjectSet<roletable>("roletables");
                }
                return _roletables;
            }
        }
        private ObjectSet<roletable> _roletables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<emptable> emptables
        {
            get
            {
                if ((_emptables == null))
                {
                    _emptables = base.CreateObjectSet<emptable>("emptables");
                }
                return _emptables;
            }
        }
        private ObjectSet<emptable> _emptables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<reviewtable> reviewtables
        {
            get
            {
                if ((_reviewtables == null))
                {
                    _reviewtables = base.CreateObjectSet<reviewtable>("reviewtables");
                }
                return _reviewtables;
            }
        }
        private ObjectSet<reviewtable> _reviewtables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<questiontable> questiontables
        {
            get
            {
                if ((_questiontables == null))
                {
                    _questiontables = base.CreateObjectSet<questiontable>("questiontables");
                }
                return _questiontables;
            }
        }
        private ObjectSet<questiontable> _questiontables;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the roletables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToroletables(roletable roletable)
        {
            base.AddObject("roletables", roletable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the emptables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemptables(emptable emptable)
        {
            base.AddObject("emptables", emptable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the reviewtables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToreviewtables(reviewtable reviewtable)
        {
            base.AddObject("reviewtables", reviewtable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the questiontables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToquestiontables(questiontable questiontable)
        {
            base.AddObject("questiontables", questiontable);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="empreviewtrackModel", Name="emptable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class emptable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new emptable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="employeeid">Initial value of the employeeid property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="date_of_joining">Initial value of the date_of_joining property.</param>
        public static emptable Createemptable(global::System.Int32 id, global::System.String name, global::System.String employeeid, global::System.String password, global::System.DateTime date_of_joining)
        {
            emptable emptable = new emptable();
            emptable.id = id;
            emptable.name = name;
            emptable.employeeid = employeeid;
            emptable.password = password;
            emptable.date_of_joining = date_of_joining;
            return emptable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String employeeid
        {
            get
            {
                return _employeeid;
            }
            set
            {
                OnemployeeidChanging(value);
                ReportPropertyChanging("employeeid");
                _employeeid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("employeeid");
                OnemployeeidChanged();
            }
        }
        private global::System.String _employeeid;
        partial void OnemployeeidChanging(global::System.String value);
        partial void OnemployeeidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_of_joining
        {
            get
            {
                return _date_of_joining;
            }
            set
            {
                Ondate_of_joiningChanging(value);
                ReportPropertyChanging("date_of_joining");
                _date_of_joining = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_of_joining");
                Ondate_of_joiningChanged();
            }
        }
        private global::System.DateTime _date_of_joining;
        partial void Ondate_of_joiningChanging(global::System.DateTime value);
        partial void Ondate_of_joiningChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String teamleader
        {
            get
            {
                return _teamleader;
            }
            set
            {
                OnteamleaderChanging(value);
                ReportPropertyChanging("teamleader");
                _teamleader = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("teamleader");
                OnteamleaderChanged();
            }
        }
        private global::System.String _teamleader;
        partial void OnteamleaderChanging(global::System.String value);
        partial void OnteamleaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String designation
        {
            get
            {
                return _designation;
            }
            set
            {
                OndesignationChanging(value);
                ReportPropertyChanging("designation");
                _designation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("designation");
                OndesignationChanged();
            }
        }
        private global::System.String _designation;
        partial void OndesignationChanging(global::System.String value);
        partial void OndesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String inserted_by
        {
            get
            {
                return _inserted_by;
            }
            set
            {
                Oninserted_byChanging(value);
                ReportPropertyChanging("inserted_by");
                _inserted_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("inserted_by");
                Oninserted_byChanged();
            }
        }
        private global::System.String _inserted_by;
        partial void Oninserted_byChanging(global::System.String value);
        partial void Oninserted_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> roleid
        {
            get
            {
                return _roleid;
            }
            set
            {
                OnroleidChanging(value);
                ReportPropertyChanging("roleid");
                _roleid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("roleid");
                OnroleidChanged();
            }
        }
        private Nullable<global::System.Int32> _roleid;
        partial void OnroleidChanging(Nullable<global::System.Int32> value);
        partial void OnroleidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="empreviewtrackModel", Name="questiontable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class questiontable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new questiontable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="question">Initial value of the question property.</param>
        public static questiontable Createquestiontable(global::System.Int32 id, global::System.String question)
        {
            questiontable questiontable = new questiontable();
            questiontable.id = id;
            questiontable.question = question;
            return questiontable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String question
        {
            get
            {
                return _question;
            }
            set
            {
                OnquestionChanging(value);
                ReportPropertyChanging("question");
                _question = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("question");
                OnquestionChanged();
            }
        }
        private global::System.String _question;
        partial void OnquestionChanging(global::System.String value);
        partial void OnquestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qid
        {
            get
            {
                return _qid;
            }
            set
            {
                OnqidChanging(value);
                ReportPropertyChanging("qid");
                _qid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qid");
                OnqidChanged();
            }
        }
        private Nullable<global::System.Int32> _qid;
        partial void OnqidChanging(Nullable<global::System.Int32> value);
        partial void OnqidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="empreviewtrackModel", Name="reviewtable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class reviewtable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new reviewtable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="employeeid">Initial value of the employeeid property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static reviewtable Createreviewtable(global::System.Int32 id, global::System.String employeeid, global::System.DateTime date)
        {
            reviewtable reviewtable = new reviewtable();
            reviewtable.id = id;
            reviewtable.employeeid = employeeid;
            reviewtable.date = date;
            return reviewtable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String employeeid
        {
            get
            {
                return _employeeid;
            }
            set
            {
                OnemployeeidChanging(value);
                ReportPropertyChanging("employeeid");
                _employeeid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("employeeid");
                OnemployeeidChanged();
            }
        }
        private global::System.String _employeeid;
        partial void OnemployeeidChanging(global::System.String value);
        partial void OnemployeeidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comment
        {
            get
            {
                return _comment;
            }
            set
            {
                OncommentChanging(value);
                ReportPropertyChanging("comment");
                _comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comment");
                OncommentChanged();
            }
        }
        private global::System.String _comment;
        partial void OncommentChanging(global::System.String value);
        partial void OncommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qid
        {
            get
            {
                return _qid;
            }
            set
            {
                OnqidChanging(value);
                ReportPropertyChanging("qid");
                _qid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qid");
                OnqidChanged();
            }
        }
        private Nullable<global::System.Int32> _qid;
        partial void OnqidChanging(Nullable<global::System.Int32> value);
        partial void OnqidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String givenby
        {
            get
            {
                return _givenby;
            }
            set
            {
                OngivenbyChanging(value);
                ReportPropertyChanging("givenby");
                _givenby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("givenby");
                OngivenbyChanged();
            }
        }
        private global::System.String _givenby;
        partial void OngivenbyChanging(global::System.String value);
        partial void OngivenbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mark
        {
            get
            {
                return _mark;
            }
            set
            {
                OnmarkChanging(value);
                ReportPropertyChanging("mark");
                _mark = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mark");
                OnmarkChanged();
            }
        }
        private Nullable<global::System.Int32> _mark;
        partial void OnmarkChanging(Nullable<global::System.Int32> value);
        partial void OnmarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String overallcomment
        {
            get
            {
                return _overallcomment;
            }
            set
            {
                OnoverallcommentChanging(value);
                ReportPropertyChanging("overallcomment");
                _overallcomment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("overallcomment");
                OnoverallcommentChanged();
            }
        }
        private global::System.String _overallcomment;
        partial void OnoverallcommentChanging(global::System.String value);
        partial void OnoverallcommentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="empreviewtrackModel", Name="roletable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class roletable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new roletable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="roleid">Initial value of the roleid property.</param>
        /// <param name="rolename">Initial value of the rolename property.</param>
        public static roletable Createroletable(global::System.Int32 id, global::System.Int32 roleid, global::System.String rolename)
        {
            roletable roletable = new roletable();
            roletable.id = id;
            roletable.roleid = roleid;
            roletable.rolename = rolename;
            return roletable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roleid
        {
            get
            {
                return _roleid;
            }
            set
            {
                OnroleidChanging(value);
                ReportPropertyChanging("roleid");
                _roleid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("roleid");
                OnroleidChanged();
            }
        }
        private global::System.Int32 _roleid;
        partial void OnroleidChanging(global::System.Int32 value);
        partial void OnroleidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rolename
        {
            get
            {
                return _rolename;
            }
            set
            {
                OnrolenameChanging(value);
                ReportPropertyChanging("rolename");
                _rolename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rolename");
                OnrolenameChanged();
            }
        }
        private global::System.String _rolename;
        partial void OnrolenameChanging(global::System.String value);
        partial void OnrolenameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="empreviewtrackModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
